### ISSUE TITLE
Last bookmarked on top of the list

### ISSUE THREAD

**Issue by lifehaschanged** [namikaze-40p/obsidian-bookmarks-caller#1]
Thank you very much for the great plugin. 
The new "search bookmarks" function is really fantastic. If I may, I would like to make a small request. Would it be possible to sort the bookmarks differently when called up? For example, I would need an overview that would include something like a "last bookmarked" function. When I then call up your new "search bookmarks" command, the bookmark that I last added to the bookmarks will be displayed at the very top of the list. That would be great.

**Comment by namikaze-40p** [comment]
Thanks for your request!

I have made sure that this is possible.
I'll consider it, please wait for a while.

**Comment by namikaze-40p** [comment]
Thanks for waiting, I released it in [v0.5.1](https://github.com/namikaze-40p/obsidian-bookmarks-caller/releases/tag/0.5.1).
Try it if you like.
